name = "nexvid-proxy"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "nexvid-db"
database_id = "a0f07533-793a-43db-86ff-5c141bf54c64"

[vars]
ALLOWED_ORIGINS = "https://nexvid.online,https://www.nexvid.online,https://*.nexvid.online,https://nexvid.pages.dev,https://*.nexvid.pages.dev,http://localhost:3000"
PROXY_ALLOWED_HOSTS = "*.febbox.com,febbox.com,*.tmdb.org,api.themoviedb.org,image.tmdb.org,sub.wyzie.ru,api.theintrodb.org,*.vixsrc.to,vixsrc.to,*.vix-content.net,vix-content.net"
SESSION_TTL_DAYS = "30"
APP_BASE_URL = "https://nexvid.online"

[dev]
port = 8787
