name = "nexvid-proxy"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "nexvid-db"
database_id = "a0f07533-793a-43db-86ff-5c141bf54c64"

[vars]
ALLOWED_ORIGINS = "https://nexvid.online,https://www.nexvid.online,https://*.nexvid.online,https://nexvid.pages.dev,https://*.nexvid.pages.dev,http://localhost:3000"
ALLOWED_HOSTS = "*.febbox.com,febbox.com,*.shegu.net,*.febbox.org,*.stream.febbox.com,*.pobreflix.com,pobreflix.com,*.tmdb.org,api.themoviedb.org,image.tmdb.org,sub.wyzie.ru,api.theintrodb.org,*.vidlink.pro,vidlink.pro,*.vodvidl.site,*.b-cdn.net,videostr.net,*.anikai.to,*.shop21pro.site,*.lab27core.site,*.hub26link.site,*.web24code.site,*.tech20hub.site,*.code29wave.site,*.pro25zone.site"
SESSION_TTL_DAYS = "30"
APP_BASE_URL = "https://nexvid.online"

[dev]
port = 8787
